# Generated by Django 5.2.1 on 2025-05-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyappRegistermodel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
            ],
            options={
                'db_table': 'myapp_registermodel',
                'managed': False,
            },
        ),
    ]
